config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # Admin urls
    path('admin/', admin.site.urls),
    
    # Allauth urls
    path('accounts/', include('allauth.urls')),
    
    # Pages app urls
    path('', include('pages.urls', namespace='pages')),
    
    # Product app urls
    path('shop/', include('product.urls', namespace='product')),
    
    # Ckeditor urls
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # Comment urls
    path('shop/', include('comment.urls', namespace='comment')),

    # category urls
    path('category/', include('category.urls', namespace='category')),


]

# serve static and media files from development server
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('contact/', views.contact_view, name='contact'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path("", views.product_list_view, name="product_list"),
    path("detail/<int:product_id>/", views.product_detail_view, name="product_detail"),
    path("search/", views.search_view, name="search"),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    
        <link rel="stylesheet" href="">
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css'>
        <link rel='stylesheet' href='https://unicons.iconscout.com/release/v2.1.9/css/unicons.css'><link rel="stylesheet" href="{% static "account/dist/style.css"%}">
    
        <!-- fonts files -->
        <link href='http://fonts.googleapis.com/css?family=Cabin:400,500,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        
        
        <!-- Font awesome css -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        
        <!-- Owl carousel css -->
        <link rel="stylesheet" href="{% static "css/owl.carousel.css"%}">
        <link rel="stylesheet" href="{% static "css/owl.transitions.css"%}">
        <link rel="stylesheet" href="{% static "css/owl.theme.css"%}">
        
        <!-- bx-slider css -->
        <link rel="stylesheet" href="{% static "css/jquery.bxslider.css"%}">
        
        <!-- bootstrap select css -->
        <link rel="stylesheet" href="{% static "css/bootstrap-select.min.css"%}">
        
        <!-- lightbox css -->
        <link rel="stylesheet" href="{% static "css/lightbox.css"%}">
        
        <!-- Revolution slider css -->
        <link href="{% static "js/rs-plugin/css/settings.css"%}" rel="stylesheet" />
        
        <!-- Bootstrap css -->
        <link rel="stylesheet" href="{% static "css/bootstrap.css"%}">
        
        <!-- Custom css -->
        <link rel="stylesheet" href="{% static "css/style.css"%}">
        <link rel="stylesheet" href="{% static "css/responsive.css"%}">

        <!-- Favicons -->
        <link rel="apple-touch-icon-precomposed" href="{% static "images/apple-touch-icon-precomposed.png"%}">
        <link rel="shortcut icon" type="image/ico" href="{% static "images/favicon.ico" %}"/>

    </head>
    <body>
        
        {% include "header.html" %}
        
        {% block content %}{% endblock %}

        {% include "footer.html" %}


        <!-- JS Files -->
        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script>
        $(function() {
            $( "#slider-range" ).slider({
            range: true,
            min: 150,
            max: 1500,
            values: [ 520, 1100 ],
            slide: function( event, ui ) {
                $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
            }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
            " - $" + $( "#slider-range" ).slider( "values", 1 ) );
        });
        </script>
	  
        <script src="{% static "js/owl.carousel.min.js"%}"></script>
        <script src="{% static "js/lightbox.min.js"%}"></script>
        <script src="{% static "js/jquery.elevatezoom.js"%}"></script>
        <script src="{% static "js/jquery.bxslider.min.js"%}"></script>
        <script type="text/javascript">
            $(document).ready(function(){
            $('.slider8').bxSlider({
                mode: 'vertical',
                slideWidth: 300,
                minSlides: 3,
                slideMargin: 10
            });
            $('.slider9').bxSlider({
                mode: 'vertical',
                slideWidth: 300,
                minSlides: 3,
                slideMargin: 10
            });
            $('.slider10').bxSlider({
                mode: 'vertical',
                slideWidth: 300,
                minSlides: 3,
                slideMargin: 10
            });
            });
        </script>
        <script src="{% static "js/bootstrap-select.min.js"%}"></script>
        <script src="{% static "js/rs-plugin/js/jquery.themepunch.plugins.min.js"%}"></script>
        <script src="{% static "js/rs-plugin/js/jquery.themepunch.revolution.min.js"%}"></script>
        <script src="{% static "js/rs-plugin/rs.home.js"%}"></script>
        <script src="{% static "js/bootstrap.min.js"%}"></script>
        <!--Opacity & Other IE fix for older browser-->
        <!--[if lte IE 8]>
            <script type="text/javascript" src="js/ie-opacity-polyfill.js"></script>
        <![endif]-->
        <script src="{% static "js/main.js"%}"></script>

        <script>
        $(function() {
            $( "#slider-range" ).slider({
            range: true,
            min: 150,
            max: 1500,
            values: [ 520, 1100 ],
            slide: function( event, ui ) {
                $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
            }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
            " - $" + $( "#slider-range" ).slider( "values", 1 ) );
        });
        </script>
    </body>
</html>

templates/footer.html
{% load static %}
{% load i18n %}


<footer class="entire_footer_area">
    <div class="footer_top_area">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-sm-6 col-xs-12">
                    <div class="footer_top_left">
                        <a href=""><i class="fa fa-envelope"></i>{% trans "signup newsletter"%}</a>
                        <input type="text" placeholder=""/>
                        <input type="submit" value="submit"/>
                    </div>
                </div>
                <div class="col-md-5 col-sm-6 col-xs-12">
                    <div class="footer_top_right">
                        <ul id="payment">
                            <li><a href="">
                                <img src="{% static "images/pay1.png"%}" alt="" />
                            </a></li>
                            <li><a href="">
                                <img src="{% static "images/pay2.png"%}" alt="" />
                            </a></li>
                            <li><a href="">
                                <img src="{% static "images/pay3.png"%}" alt="" />
                            </a></li>
                            <li><a href="">
                                <img src="{% static "images/pay4.png"%}" alt="" />
                            </a></li>
                            <li><a href="">
                                <img src="{% static "images/pay5.png"%}" alt="" />
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_area">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="single_widget">
                        <h5>{% trans "information"%}</h5>
                        <div class="wid_line"></div>
                        <ul class="widget_nav">
                            <li><a href="">{% trans "New Products"%}</a></li>
                            <li><a href="">{% trans "Top Seller"%}</a></li>
                            <li><a href="">{% trans "Special"%}</a></li>
                            <li><a href="">{% trans "Manufactures"%}</a></li>
                            <li><a href="">{% trans "Suppliers"%}</a></li>
                            <li><a href="">{% trans "Our Stores"%}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="single_widget">
                        <h5>{% trans "my account"%}</h5>
                        <div class="wid_line"></div>
                        <ul class="widget_nav">
                            <li><a href="">{% trans "My Account"%}</a></li>
                            <li><a href="">Personal Information</a></li>
                            <li><a href="">Addresses</a></li>
                            <li><a href="">Discounts</a></li>
                            <li><a href="">Order History</a></li>
                            <li><a href="">Your Vouchers</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="single_widget">
                        <h5>customer service</h5>
                        <div class="wid_line"></div>
                        <ul class="widget_nav">
                            <li><a href="">Help & Contact</a></li>
                            <li><a href="">Shipping & Taxes</a></li>
                            <li><a href="">Return Policy</a></li>
                            <li><a href="">Careers</a></li>
                            <li><a href="">Affliates</a></li>
                            <li><a href="">Legal Notice</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="single_widget">
                        <h5>contact Info</h5>
                        <div class="wid_line"></div>
                        <address>
                            Address : 44 New Design Street,<br>
                            Melbourne 005<br>
                            Phone : (01) 800 433 633<br>
                            Email : info@Example.com
                        </address>
                        <ul class="wid_social">
                            <li><a class="fa fa-facebook" href=""></a></li>
                            <li><a class="fa fa-twitter" href=""></a></li>
                            <li><a class="fa fa-google-plus" href=""></a></li>
                            <li><a class="fa fa-pinterest" href=""></a></li>
                            <li><a class="fa fa-rss" href=""></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bottom_area">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="footer_bottom">
                        <p>Copyright &copy; 2015 <a href="index.html">Men’swaer</a>. All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
{% load i18n %}

<div class="header_top">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="header_top_left">
                    <img src="{% static "images/car.png"%}" alt="Header Car Icon" />
                    <p>{% trans "get free! shipping on order over" %} <span>$100</span></p>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="header_top_right floatright">
                    <p><a href="">{% trans "login" %}</a> / <a href="">{% trans "register" %}</a></p>
                    <nav class="currency alignleft">
                        <ul>
                            <li><a href="">USD</a>
                                <ul class="currency-dropdown">
                                    <li><a href="">EUR</a></li>
                                    <li><a href="">GBP</a></li>
                                    <li><a href="">CAD</a></li>
                                    <li><a href="">AUD</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                    <div class="top-flag alignleft">
                        <img src="{% static "images/flag.png"%}" alt="Flags" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="header">
    <div class="container">
        <div class="row">
            <form method="post" action="{% url "product:search" %}">
                {% csrf_token %}
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="header_left floatleft">
                        <a class="fa fa-search" href=""></a>
                        <input type="text" name="search" placeholder="{% trans "search" %}"/>
                    </div>
                </div>
            </form>
            <div class="col-md-6 col-sm-5 col-xs-12">
                <div class="header_center">
                    <a href="index.html"><img src="{% static "images/logo.png"%}" alt="Site Logo" /></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="header_right floatright">
                    <ul class="checkout">
                        <li><a href="checkout.html"><i class="fa fa-heart-o"></i>{% trans "wishlist"%}</a></li>
                        <li class="mobi_right_li"><a href="checkout.html"><i class="fa fa-shopping-cart"></i>{% trans "checklist"%}</a></li>
                    </ul>
                    <div class="w_likes">
                        <span>3</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="nav_area">
    <div class="container">
    <div class="nav_left floatleft">
        <a href="#">{% trans "category" %}<i class="fa fa-bars"></i></a>
        <ul id="sub-menu3">
            {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                    <ul id="sub-menu2">
                        {% for item in category.parent_category.all %}
                            <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="nav_center">
        <nav class="mainmenu">
            <ul id="nav">
                <li
                    ><a href="{% url "pages:home" %}">{% trans "Home" %}</a>
                </li>
                <li>
                    <a href="{% url "product:product_list" %}">{% trans "shop" %}</a>
                </li>
                {% comment %} 
                    <li><a href="category-1.html">accessories</a>
                        <ul id="sub-menu">
                            <li><a href="">check shirts</a></li>
                            <li><a href="">denim shirts</a></li>
                            <li><a href="">long sleeve shirts</a></li>
                            <li><a href="">plain shirts</a></li>
                            <li><a href="">printed shirts</a></li>
                            <li><a href="">short sleeve shirts</a></li>
                            <li class="last-child"><a href="">shortsleeve denim shirts</a></li>
                        </ul>
                    </li> 
                {% endcomment %}
                <li><a href="{% url "pages:contact" %}">{% trans "Contact page"%}</a></li>
                {% comment %} 
                    <li><a href="#">{% trans "pages" %}</a>
                        <ul id="sub-menu5">
                            <li><a href="category-1.html">Shop Page With Filter</a></li>
                            <li><a href="category-2.html">Shop Page Without Filter</a></li>
                            <li><a href="checkout.html">Checkout page</a></li>
                            <li><a href="cart.html">Cart page</a></li>
                            <li><a href="single-blog.html">Blog single</a></li>
                            <li><a href="contact.html">Contact page</a></li>
                            <li><a href="404.html">404 page</a></li>
                        </ul>
                    </li> 
                {% endcomment %}
                <li><a href="blog.html">{% trans "Blog"%}</a></li>
            </ul>
        </nav>
    </div>
    <div class="nav_right floatright">
        <a href="cart.html"><img src="{% static "images/bag.png"%}" alt="Bag" />{% trans "cart:" %} 2 {% trans "items" %}</a>
        <div class="cart_menu">
            <div class="cart_items">
                <div class="c_item_img floatleft">
                    <a href="product-detail.html"><img src="{% static "images/c_item1.jpg"%}" alt="" /></a>
                </div>
                <div class="c_item_totals floatleft">
                    <div class="c_item_totals_detail floatleft">
                        <a href="product-detail.html"><h5>men’s fashion blue jean coat</h5></a>
                        <span>2 x $ 130.00</span>
                    </div>
                    <div class="close_icon_cart floatleft">
                        <img src="{% static "images/close.png"%}" alt="" />
                    </div>
                </div>
            </div>
            <div class="cart_totals">
                <div class="c_totals_left floatleft">
                    <p>{% trans "Free shipping" %}</p>
                </div>
                <div class="c_totals_right floatleft">
                    <p>{% trans "total" %}   {% trans "$" %}350</p>
                </div>
            </div>
            <div class="cart_view_bottom">
                <div class="c_totals_left floatleft">
                    <a href="cart.html">{% trans "View Cart" %}</a>
                </div>
                <div class="c_totals_right floatleft">
                    <a href="checkout.html">{% trans "Check Out" %}</a>
                </div>
            </div>
        </div>
    </div>
    
    
        <!-- MOBILE ONLY CONTENT -->
        <div class="only-for-mobile">
            <ul class="ofm">
                <li class="m_nav"><i class="fa fa-bars"></i> Navigation</li>
            </ul>

            <!-- MOBILE MENU -->
            <div class="mobi-menu">
                <div id='cssmenu'>
                    <ul>
                        <li class='has-sub'>
                            <a href='index.html'><span>Home</span></a>
                            <ul class="sub-nav">
                                <li><a href="index.html"><span>Home 1</span></a></li>
                                <li><a href="index-2.html"><span>Home 2</span></a></li>
                            </ul>
                        </li>

                        <li class='has-sub'>
                            <a href='category-1.html'><span>category</span></a>
                            <ul>
                                <li class='has-sub'>
                                    <a href='#'><span>Shirts</span></a>
                                    <ul>
                                        <li><a href="#"><span>check shirts</span></a></li>
                                        <li><a href="#"><span>denim shirts</span></a></li>
                                        <li><a href="#"><span>long sleeve shirts</span></a></li>
                                        <li><a href="#"><span>denim shirts</span></a></li>
                                        <li class="last"><a href="./#"><span>long sleeve shirts</span></a></li>
                                    </ul>
                                </li>
                                <li class='has-sub'>
                                    <a href='#'><span>T Shirts</span></a>
                                    <ul>
                                        <li><a href="#"><span>plain T-shirt</span></a></li>
                                        <li><a href="#"><span>printed T-shirt</span></a></li>
                                        <li><a href="#"><span>sports T-shirt</span></a></li>
                                        <li><a href="#"><span>striped T-shirt</span></a></li>
                                        <li class='last'><a href="#"><span>V-Neck T-Shirt</span></a></li>
                                    </ul>
                                </li>
                                <li class='has-sub'>
                                    <a href='#'><span>trousers fit</span></a>
                                    <ul>
                                        <li><a href="#"><span>flexible waist</span></a></li>
                                        <li><a href="#"><span>regular fit</span></a></li>
                                        <li><a href="#"><span>slim fit</span></a></li>
                                        <li><a href="#"><span>tailored fit</span></a></li>
                                        <li class='last'><a href="#"><span>tight fit</span></a></li>
                                    </ul>
                                </li>
                                <li class="img-nav">
                                    <div class="container">
                                        <div class="clearfix"></div>
                                        <div class="space20"></div>
                                        <div class="clearfix"></div>
                                        <div class="row in1">
                                            <div class="col-md-6">
                                                <a href="#"><img src="{% static "images/menu_cat.png"%}" class="img-responsive" alt=""/></a>
                                            </div>
                                            <div class="col-md-6">
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="space20"></div>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="space20"></div>
                                        <div class="clearfix"></div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href='category-2.html'><span>shop</span></a>
                        </li>
                        <li class='has-sub'>
                            <a href='category-1.html'><span>accessories</span></a>
                            <ul class="sub-nav">
                                <li><a href="#"><span>check shirts</span></a></li>
                                <li><a href="#"><span>denim shirts</span></a></li>
                                <li><a href="#"><span>long sleeve shirts</span></a></li>
                                <li><a href="#"><span>plain shirts</span></a></li>
                                <li><a href="#"><span>printed shirts</span></a></li>
                                <li><a href="#"><span>short sleeve shirts</span></a></li>
                                <li><a href="#"><span>shortsleeve denim shirts</span></a></li>
                            </ul>
                        </li>
                        <li class='has-sub'>
                            <a href='#'><span>pages</span></a>
                            <ul id="sub-nav">
                                <li><a href="category-1.html">Category page</a></li>
                                <li><a href="category-2.html">Category page without filter</a></li>
                                <li><a href="checkout.html">Checkout page</a></li>
                                <li><a href="cart.html">Cart page</a></li>
                                <li><a href="product-detail.html">Product detail page</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="single-blog.html">Blog single</a></li>
                                <li><a href="contact.html">Contact page</a></li>
                                <li><a href="404.html">404 page</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href='blog.html'><span>Blog</span></a>
                        </li>
                        <li>
                            <a href='cart.html'><span>cart</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- MOBILE ONLY CONTENT -->

    </div>
</div>